### PR TITLE
Feat/gulp license

### PR DESCRIPTION
**Pull request by martinheidegger**
This PR adds a gulp script that modifies pngs/jpegs/svgs to contain the correct license based off a `LICENSE` document in the project root.

### CODE REVIEW

**Review by dkastl — APPROVED** [review]
Good idea!

**Comment by Tannybunny** [comment]
"- [Georepublic](https://georepublic.info)
        - assets/images/**/*"

at the moment there are images in this folder, that are not made by Georepublic e.g EU-Flag, Ledger Logo, etc.
So we shouldnt write something about the License in the meta data of these files I guess ? 
We could reorganize these images into a different folder

**Comment by martinheidegger** [comment]
I added support for removing a license if the license is changed in a15a719. You should be able to freely set the license for all files.

**Comment by martinheidegger** [comment]
I just squashed the commit and made sure that following things are maintained:

1. you can change the license without recompressing the images
2. you can removed a license from the LICENSE file and it will remove the license declaration from the affected files
3. the changed files will be logged

**Comment by martinheidegger** [comment]
@Tannybunny is the license file ready as is?

**Pull request merged**
