### PR TITLE
Code highlighting

### PR DESCRIPTION
**Pull request by Torgian**
Added code highlighting. I found an online tool here: https://tohtml.com/jScript/

However, there's also a library called Prism. I wanted to check if [Prism](https://prismjs.com/download.html#themes=prism-okaidia&languages=clike+javascript) would be preferable. 

Of course, with the inline styling, it'll work even if someone doesn't have javascript enabled.

### CODE REVIEW

**Comment by martinheidegger** [comment]
This does basically work and it should be okay _(if @consento-org/design is okay with the colors, screenshot would be good)_

What I would look out for in a tool though, is that it runs through the command line. (npm) - this way the transformation can happen offline and we are not causing server costs to someone else. It is also noticable that the design specifies each style inline, instead of a css clause. this makes theming later on probably a bit problematic. What is more noticable though is that the code is formatted as JavaScript code when it is actually typescript code.

**Comment by Torgian** [comment]
I found a library ( highlight.js ) that used a bunch of different code editor styles. I found this css style [here](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/tomorrow-night-bright.min.css) that is called 'tomorrow-night' that looks nice. I modified the css to fit our needs and made a new scss file. Then added some classes to the code block. Please let me know what you think. Refer to commits: [1](https://github.com/consento-org/consento-website/pull/59/commits/97a3ec683504e818fe90c63ffd6f3031541048ad) and [2](https://github.com/consento-org/consento-website/pull/59/commits/7c10dbc211248eb8f562624d6758b18c2f3ba86c)

Screen Shot 2020-02-14 at 3 52 50 PM

**Review by martinheidegger — CHANGES_REQUESTED** [review]
This is a much better effort but it has three issues:

1. It does not have Typescript support
2. There is manual work to do in case you want to update the code
3. It is not possible to run that offline.

I was under the impression that the JavaScript community would certainly provide a better tool since last time I checked (years ago). To mitigate the issue, I just now published [`@leichtgewicht/prism-cli`](https://github.com/martinheidegger/prism-cli/) which adds the `--html` option to get [prism](https://prismjs.com/) output as html code. You can install the patched `prism-cli` now locally using `npm install @leichtgewicht/prism-cli -g` or directly using ` npx @leichtgewicht/prism-cli`.

You can then transform the code from clipboard _(if you are using `npx`)_ on mac using:

`pbpaste | npx @leichtgewicht/prism-cli -f typescript --html`

and replace the content of the clipboard using:

`pbpaste | npx @leichtgewicht/prism-cli -f typescript --html | pbcopy`

It will generate html output that can be styled using/or-customizing one the of [the official prism templates](https://github.com/PrismJS/prism/tree/master/themes).

**Comment by Torgian** [comment]
I had to change the terminal command slightly: 

`npx @leichtgewicht/prism-cli -f npstyle.ts --html -l typescript`

I had to provide a file; it could not read from the clipboard for some reason. That said, the output I received was similar to what I was doing earlier. Is there a css file I need?


```
<pre class="language-typescript"><span class="token function">confirm</span> <span class="token punctuation">(</span>accept<span class="token operator">:</span> IHandshakeAcceptMessage<span class="token punctuation">)</span><span class="token operator">:</span> ICancelable<span class="token operator"><</span>IHandshakeConfirmation<span class="token operator">></span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> cancelable<span class="token operator"><</span>IHandshakeConfirmation<span class="token punctuation">,</span> HandshakeInit<span class="token operator">></span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token operator">*</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">const</span> secretKey <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">yield</span> crypto<span class="token punctuation">.</span><span class="token function">computeSecret</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>confirmKey<span class="token punctuation">,</span> Buffer<span class="token punctuation">.</span><span class="token keyword">from</span><span class="token punctuation">(</span>accept<span class="token punctuation">.</span>token<span class="token punctuation">,</span> <span class="token string">'base64'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">as</span> Uint8Array
        <span class="token keyword">const</span> bob <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">yield</span> <span class="token function">createSender</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">as</span> ISender
        <span class="token keyword">const</span> sendKey <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">yield</span> crypto<span class="token punctuation">.</span><span class="token function">decrypt</span><span class="token punctuation">(</span>secretKey<span class="token punctuation">,</span> Buffer<span class="token punctuation">.</span><span class="token keyword">from</span><span class="token punctuation">(</span>accept<span class="token punctuation">.</span>secret<span class="token punctuation">,</span> <span class="token string">'base64'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">as</span> IEncodable
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token punctuation">(</span>sendKey <span class="token keyword">instanceof</span> <span class="token class-name">Uint8Array</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
          <span class="token keyword">throw</span> Object<span class="token punctuation">.</span><span class="token function">assign</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'Expected buffer in decrypted message'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> code<span class="token operator">:</span> <span class="token string">'invalid-message'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">const</span> sender <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">yield</span> <span class="token function">createSenderFromSendKey</span><span class="token punctuation">(</span>sendKey<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token keyword">as</span> ISender
        <span class="token keyword">return</span> <span class="token keyword">yield</span> <span class="token keyword">new</span> <span class="token class-name">HandshakeConfirmation</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
          connection<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Connection</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
            sender<span class="token punctuation">,</span>
            receiver<span class="token operator">:</span> bob<span class="token punctuation">.</span><span class="token function">newReceiver</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
          <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
          <span class="token comment">// In case you are wondering why we not just simply return "bob" as sender</span>
          <span class="token comment">// but instead pass it in two messages: the reason is that without this step</span>
          finalMessage<span class="token operator">:</span> bob<span class="token punctuation">.</span>sendKey
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token keyword">this</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
```

**Comment by martinheidegger** [comment]
> It will generate html output that can be styled using/or-customizing one the of the official  [the official prism templates](https://github.com/PrismJS/prism/tree/master/themes).

**Comment by Torgian** [comment]
I used the following css : [tomorrow night](https://github.com/PrismJS/prism/blob/master/themes/prism-tomorrow.css)

Refer to this [commit](https://github.com/consento-org/consento-website/pull/59/commits/5c43fd043b18a3a3607717f3be5081165e022d74) 

How does it look?

Screen Shot 2020-02-17 at 4 56 08 PM
Screen Shot 2020-02-17 at 4 56 20 PM

**Comment by martinheidegger** [comment]
Good, now two tasks left:

1. Please rebase & force-push the branch to fix the conflict
2. Document the way you added the code in a place good to find next time

**Review by martinheidegger — APPROVED** [review]

**Pull request merged**
